cppgc_headers = [
  'allocation.h',
  'common.h',
  'cross-thread-persistent.h',
  'custom-space.h',
  'default-platform.h',
  'explicit-management.h',
  'garbage-collected.h',
  'heap-consistency.h',
  'heap-handle.h',
  'heap-state.h',
  'heap-statistics.h',
  'heap.h',
  'liveness-broker.h',
  'macros.h',
  'member.h',
  'name-provider.h',
  'object-size-trait.h',
  'persistent.h',
  'platform.h',
  'prefinalizer.h',
  'process-heap-statistics.h',
  'sentinel-pointer.h',
  'source-location.h',
  'tagged-member.h',
  'testing.h',
  'trace-trait.h',
  'type-traits.h',
  'visitor.h',
]

install_headers(cppgc_headers, subdir: install_header_subdir / 'cppgc')

subdir('internal')
